apply plugin: 'antlr'

dependencies {

  api('org.antlr.antlr-runtime:3.5.2') {
        exclude group: 'org.antlr', module: 'stringtemplate'
  }
//  compile "org.ow2.asm:asm-debug-all:5.0.3"
  api project(':d2j-base-cmd')
  api project(':ams')
  antlr "org.antlr:antlr:3.5.2"
}

sourceSets.main.antlr.srcDirs = ['src/main/antlr3']
